# Site settings
title: Bonan Liu's CV 
description: Bonan Liu, a software engineer with hands-on experience in distributed system and cloud computing.
favicon: /assets/img/avatar.JPG
baseurl: https://liubonan.github.io
url: https://liubonan.github.io
rss_url: /pages/atom.xml
google_analytics: UA-105173916-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Bonan Liu
  title: Software Engineer
  address: Seattle, WA, United States
  email: liubonan#liubonan.com
  link: http://liubonan.info
  weibo:  
  github: liubonan
  linkedin: liubonan
  twitter: 
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow:
  workHistory:
    - work1:
      company: Google Inc.
      location: Greater Seattle Area, WA, US
      title: Software Engineer
      started: 2015
      duration: (2015 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Microsoft Corp.
      location: Greater Seattle Area, WA, US
      title: Software Development Engineer
      started: 2013
      duration: (2013 - 2015)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  educationHistory:
    - education1:
      organization: Columbia University
      location: New York, NY, US
      degree: Master of Science
      major: Computer Science
      started: 2011
      duration: (2011 - 2013)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - education2:
      organization: Sichuan University
      location: Chengdu, Sichuan, China
      degree: Bachelor of Engineering
      major: Compuater Science and Technology
      started: 2007
      duration: (2007-2011)
      description: TBD
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
  programmingSkills:
    - skill1:
      name: Java 
      percentage: 100%
    - skill2:
      name: Go
      percentage: 90%
    - skill3:
      name: Python
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%
